---
kind: pipeline
type: docker
name: notify-hydra

steps:
  - name: Notify hydra
    image: nixery.dev/shell/curl
    commands:
      - curl --get --data-urlencode "jobsets=darkkirb:rkb1-firmware" https://hydra.chir.rs/api/push
trigger:
  event:
    - push
  branch:
    - main
